[project]
name = "fde-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "google-genai>=2.27.0",
    "python-dotenv>=1.2.4",
    "uvicorn>=0.54.0",
]

[project.scripts]
fde-hub = "fde_hub:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
